spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    name: mydata
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/mydata?userUnicode=true&characterEncoding=utf-8&userSSL=true&serverTimezone=UTC
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
